sonar.projectKey=cricket-scorecard-backend
sonar.projectName=cricket-scorecard-backend

sonar.host.url=http://localhost:9000
sonar.token=sqp_cb8db8382b6033c1d929b135240b91d826ebc531
sonar.sources=src
sonar.java.binaries=target/classes

